apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: default
data:
  krakend.json: |
    {
      "version": 3,
      "name": "KrakenD API Gateway",
      "port": 8081,
      "timeout": "30s",
      "endpoints": [
        {
          "endpoint": "/auth/signup",
          "method": "POST",
          "output_encoding": "no-op",
          "input_headers": [ "Content-Type"],
          "backend": [
            {
              "host": ["http://content-moderation-service"],
              "sd": "static",
              "url_pattern": "/auth/signup",
              "method": "POST",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/auth/login",
          "method": "POST",
          "output_encoding": "no-op",
          "input_headers": ["Content-Type"],
          "backend": [
            {
              "host": ["http://content-moderation-service"],
              "sd": "static",
              "url_pattern": "/auth/login",
              "method": "POST",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/posts",
          "method": "GET",
          "output_encoding": "no-op",
          "extra_config": {
            "qos/ratelimit/router": {
              "max_rate": 100,
              "client_max_rate": 6,
              "strategy": "header",
              "key": "Authorization"
            }
          },
          "input_headers": ["Authorization", "Content-Type"],
          "backend": [
            {
              "host": ["http://content-moderation-service"],
              "sd": "static",
              "url_pattern": "/posts",
              "method": "GET",
              "encoding": "json",
              "extra_config": {
                "proxy": {
                  "response": {
                    "decoder": {
                      "name": "json",
                      "config": {
                        "collection": true
                      }
                    }
                  }
                }
              }
            }
          ]
        },
        {
          "endpoint": "/comment",
          "method": "POST",
          "output_encoding": "no-op",
          "extra_config": {
            "qos/ratelimit/router": {
              "max_rate": 100,
              "client_max_rate": 6,
              "strategy": "header",
              "key": "Authorization"
            }
          },
          "input_headers": ["Authorization", "Content-Type"],
          "timeout": "30s",
          "backend": [
            {
              "host": ["http://content-moderation-service"],
              "sd": "static",
              "url_pattern": "/comment",
              "method": "POST",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/review",
          "method": "POST",
          "output_encoding": "no-op",
          "extra_config": {
            "qos/ratelimit/router": {
              "max_rate": 100,
              "client_max_rate": 6,
              "strategy": "header",
              "key": "Authorization"
            }
          },
          "input_headers": ["Authorization", "Content-Type"],
          "backend": [
            {
              "host": ["http://content-moderation-service"],
              "sd": "static",
              "url_pattern": "/review",
              "method": "POST",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/moderation",
          "method": "POST",
          "output_encoding": "no-op",
          "extra_config": {
            "qos/ratelimit/router": {
              "max_rate": 100,
              "client_max_rate": 6,
              "strategy": "header",
              "key": "Authorization"
            }
          },
          "input_headers": ["Authorization", "Content-Type"],
          "backend": [
            {
              "host": ["http://content-moderation-service"],
              "sd": "static",
              "url_pattern": "/moderation",
              "method": "POST",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/notify",
          "method": "GET",
          "output_encoding": "no-op",
          "input_headers": ["Authorization", "Content-Type"],
          "backend": [
            {
              "host": ["http://notf-service"],
              "sd": "static",
              "url_pattern": "/notify",
              "method": "GET",
              "encoding": "json"
            }
          ]
        }
      ],
      "extra_config": {
        "security/cors": {
          "allow_origins": [
            "https://content-moderation-frontend.vercel.app/",
            "*"
          ],
          "allow_headers": [
            "Content-Length",
            "Content-Type",
            "Location",
            "User-Agent",
            "Authorization",
            "X-Forwarded-For"
          ],
          "expose_headers": [
            "Content-Length",
            "Authorization",
            "User-Agent",
            "X-Forwarded-For",
            "Set-Cookie"
          ],
          "allow_methods": [
            "GET",
            "HEAD",
            "POST",
            "PUT",
            "OPTIONS",
            "PATCH",
            "DELETE"
          ],
          "max_age": "12h",
          "allow_credentials": true
        },
        "proxy": {
          "disable_error_status_check": true
        }
      }
    }
