name: Build, Push Docker Image, and Deploy Krakend to GKE

on:
  push:
    branches:
      - main

jobs:
  krakend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 9874694577/krakend:${{ github.sha }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: autopilot-cluster-1
          location: asia-south1

      - name: Apply Krakend ConfigMap
        run: |
          kubectl apply -f krakend-configmap.yaml

      - name: Apply Krakend Deployment and Service
        run: |
          kubectl apply -f krakend-deployment.yaml
          kubectl apply -f krakend-service.yaml

      - name: Update Krakend image with commit SHA
        run: |
          kubectl set image deployment/krakend-deployment krakend=9874694577/krakend:${{ github.sha }}
          kubectl rollout status deployment/krakend-deployment
